# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "NodeJS and Yarn versions:"
      - node --version
      - yarn --version
  pre_build:
    commands:
      - echo Installing dependencies with Yarn...
      - yarn
  build:
    commands:
      - echo Build started on `date`
      - yarn build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  name: outline-build-$CODEBUILD_BUILD_NUMBER.zip
  s3-prefix: codebuild/
  files:
    - build/**/*
    - package.json
    - yarn.lock
    - node_modules/**/*
    - .ebextensions/**/*
eb_codebuild_settings:
  CodeBuildServiceRole: code-build-role
  ComputeType: BUILD_GENERAL1_SMALL
  Image: aws/codebuild/standard:4.0
  Timeout: 60



